name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  PROJECTS_BUILD: './src/Milochau.Core.sln'
  PROJECTS_TESTS: './src/Milochau.Core.sln'
  DOTNET_VERSION: 5.0.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x # Explicitly reference .NET Core 3.1 for Functions compatibility
      - name: Build and test projects
        uses: milochaucom/github-actions/build/netcore@v1
        with:
          projectsToBuild: ${{ env.PROJECTS_BUILD }}
          projectsToTest: ${{ env.PROJECTS_TESTS }}
