name: Deploy libraries

on:
  workflow_dispatch:

env:
  PROJECTS_BUILD: './src/Milochau.Core.sln'
  PROJECTS_SDK: './src/Milochau.Core.Sdk.sln'
  VERSION_FILE: './src/Directory.Build.props'
  NUGET_URL: 'https://nuget.pkg.github.com/milochaucom/index.json'
  DOTNET_VERSION: 5.0.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy libraries
        id: actions_release
          uses: milochaucom/github-actions/release/nuget@main
        with:
          projectsToBuild: ${{ env.PROJECTS_BUILD }}
          projectsToPublish: ${{ env.PROJECTS_SDK }}
          versionFile: ${{ env.VERSION_FILE }}
          nugetUrl: ${{ env.NUGET_URL }}
          dotnetVersion: ${{ env.DOTNET_VERSION }}
